export const CART_ADD = 'Cart/ADD'
export const CART_ADD_SUCCESS = 'Cart/ADD_SUCCESS'
export const CART_REMOVE = 'Cart/REMOVE'
export const CART_UPDATE_AMOUNT = 'Cart/UPDATE_AMOUNT'
export const CART_UPDATE_AMOUNT_SUCCESS = 'Cart/UPDATE_AMOUNT_SUCCESS'
